---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/common/tasks/centos.yml

- name: be sure we have the latest version of all packages
  yum:
    state: latest
    name: "*"
    update_cache: yes

- name: be sure the epel-release
  yum:
    state: latest
    name: epel-release

- name: be sure dependencies are installed
  yum:
    state: latest
    name:
      - ca-certificates
      - python3
