---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/common/tasks/debian.yml

- name: be sure we have the latest version of all packages
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: be sure the dependencies are installed
  apt:
    state: latest
    name:
      - ca-certificates
      - python3
      - python3-pip
      - auditd
      - audispd-plugins

- name: be sure auditd is started and enabled
  systemd:
    name: auditd
    state: started
    enabled: yes
    daemon_reload: yes
