---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/common/tasks/debian.yml

- name: be sure we have the latest version of all packages
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: be sure the dependencies are installed
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg2
      - python3
      - python3-pip
    state: latest
