---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/common/tasks/main.yml

- include: "{{ ansible_facts['distribution'] | lower }}.yml"

- name: be sure swap is disabled
  block:
    - shell: swapoff -a
    - mount:
        name: swap
        fstype: swap
        state: absent

- name: be sure the /etc/issue is set as the ssh login banner
  block:

    - name: Deduplicate values from /etc/ssh/sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        create: false
        regexp: (?i)^\s*Banner\s+
        state: absent

    - name: Insert correct line to /etc/ssh/sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        create: true
        line: Banner /etc/issue
        state: present
        insertbefore: ^Match
        validate: /usr/sbin/sshd -t -f %s

    - name: be sure to set the login banner
      template:
        src: issue.j2
        dest: /etc/issue

- name: reboot to apply updates
  reboot: {}

- name: wait for machine to come back
  wait_for_connection: {}

