---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/common/tasks/redhat.yml

- name: be sure the disks are configured
  set_fact:
    secondary_disk_format: xfs
    secondary_disk_name: /dev/nvme1n1
    secondary_disk_partitions:
      - name: rhel-var
        path: /var
        tmp: /srv/var
        part_start: 0%
        part_end: 20%
      - name: rhel-var-log-audit
        path: /var/log/audit
        tmp: /srv/varlogaudit
        part_start: 20%
        part_end: 30%
      - name: rhel-home
        path: /home
        tmp: /srv/home
        part_start: 30%
        part_end: 40%
      - name: rhel-tmp
        path: /tmp
        tmp: /srv/tmp
        part_start: 40%
        part_end: 50%
      - name: docker-var-lib
        path: /var/lib/docker
        tmp: /srv/varlibdocker
        part_start: 50%
        part_end: 90%

- name: be sure repo_gpgcheck is not enabled as it is not supported
  ini_file:
    dest: /etc/yum.conf
    section: main
    option: repo_gpgcheck
    value: '0'
    create: false
  
- name: be sure we have the latest version of all packages
  yum:
    name: "*"
    state: latest

# https://access.redhat.com/articles/4599971
- name: be sure all of the redhat repos are enabled
  shell: "yum-config-manager --enable {{ item }}"
  with_items:
    - rhel-7-server-rhui-rpms
    - rhel-7-server-rhui-rh-common-rpms
    - rhel-7-server-rhui-extras-rpms

- name: be sure the dependencies are installed
  yum:
    state: latest
    name:
      - ca-certificates
      - curl
      - yum-utils
      - audit
      - audit-libs
      - parted

- include_tasks: disks.yml

- name: be sure auditd is started and enabled
  systemd:
    name: auditd
    state: started
    enabled: yes
    daemon_reload: yes
