---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/common/tasks/redhat.yml

- name: be sure repo_gpgcheck is not enabled as it is not supported
  ini_file:
    dest: /etc/yum.conf
    section: main
    option: repo_gpgcheck
    value: '0'
    create: false
  
- name: be sure we have the latest version of all packages
  yum:
    name: "*"
    state: latest

# https://access.redhat.com/articles/4599971
- name: be sure all of the redhat repos are enabled
  shell: "yum-config-manager --enable {{ item }}"
  with_items:
    - rhel-7-server-rhui-rpms
    - rhel-7-server-rhui-rh-common-rpms
    - rhel-7-server-rhui-extras-rpms

- name: be sure the dependencies are installed
  yum:
    state: latest
    name:
      - ca-certificates
      - curl
      - yum-utils
      - wget

