---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/aws-ssm-agent/tasks/redhat.yml

- name: be sure the ssm agent is installed
  yum:
    name: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
    state: latest
    disable_gpg_check: yes
  
- name: be sure the ssm agent is started and enabled
  systemd:
    name: amazon-ssm-agent
    state: started
    enabled: yes
    daemon_reload: yes
