---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/docker/tasks/centos.yml

- name: be sure other versions of docker are not present
  yum:
    state: absent
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine

- name: be sure the docker dependencies are installed
  yum:
    state: latest
    update_cache: yes
    name:
      - device-mapper-persistent-data
      - lvm2

- name: be sure the docker repository is configured
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: be sure the latest version of docker is installed
  yum:
    state: latest
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
