---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/docker/tasks/main.yml

- name: be sure the docker folder is created and ready to be mounted
  shell: rm -rf /var/lib/docker && mkdir -p /var/lib/docker

- set_fact:
    docker_disk_name: /dev/nvme0n1
  when: ansible_facts['os_family'] == 'Debian'

- set_fact:
    docker_disk_name: /dev/nvme1n1
  when: ansible_facts['os_family'] == 'RedHat'

- name: be sure the docker partition is formated
  filesystem:
    fstype: ext4
    dev: "{{ docker_disk_name }}"

- name: be sure the docker partition is mounted
  mount:
    src: "{{ docker_disk_name }}"
    path: /var/lib/docker
    fstype: ext4
    state: mounted

- name: run operating system specific commands
  include: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: run the docker cis benchmark
  include: cis-benchmark.yml
