---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/docker/tasks/sysctl.yml

- name: be sure vm.swappiness=0
  sysctl:
    name: vm.swappiness
    value: '0'
    state: present

- name: be sure vm.overcommit_memory=1
  sysctl:
    name: vm.overcommit_memory
    value: '1'
    state: present

- name: be sure net.ipv4.ip_local_port_range=1024 65000
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: '1024 65000'
    state: present

- name: be sure net.core.somaxconn=10000
  sysctl:
    name: net.core.somaxconn
    value: '10000'
    state: present


- name: be sure net.ipv4.tcp_keepalive_time=600
  sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: '600'
    state: present

- name: be sure net.ipv4.ip_forward=1
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present

- name: be sure fs.may_detach_mounts=1
  sysctl:
    name: fs.may_detach_mounts
    value: '1'
    state: present
