---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: eks ami
  hosts: all
  roles:
    - RedHatOfficial.rhel7_stig
    - common
    - docker
    - eks
