---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: install base components
  hosts: all
  roles:
    - common
    - hardening
    - aws-cli
    - docker
    - eks
    - cleanup
