---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/eks/tasks/iptables.yml

- name: be sure forwarding is enabled via iptables
  block:
    - file:
        path: /etc/sysconfig
        state: directory
    - shell: /sbin/iptables-save > /etc/sysconfig/iptables
  when: ansible_facts['os_family'] == "RedHat"

- name: be sure forwarding is enabled via iptables
  block:
    - file:
        path: /etc/iptables
        state: directory
    - shell: /sbin/iptables-save > /etc/iptables/rules.v4
  when: ansible_facts['os_family'] == "Debian"

- name: be sure we have the latest version of the iptables restore from aws
  copy:
    src: iptables-restore.{{ ansible_facts['os_family'] | lower }}.service
    dest: /etc/systemd/system/iptables-restore.service

- name: be sure the iptables-restore is started and enabled
  systemd:
    name: iptables-restore
    state: started
    enabled: yes
    daemon_reload: yes
