---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/eks/tasks/iptables.yml

- name: be sure forwarding is enabled via iptables
  shell: /sbin/iptables-save > /etc/sysconfig/iptables

- name: be sure we have the latest version of the iptables restore from aws
  get_url:
    url: https://raw.githubusercontent.com/awslabs/amazon-eks-ami/master/files/iptables-restore.service
    dest: /etc/systemd/system/iptables-restore.service

- name: be sure the iptables-restore is started and enabled
  systemd:
    name: iptables-restore
    state: started
    enabled: yes
    daemon_reload: yes
