---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/eks/tasks/kubelet.yml

- name: be sure the kubelet folders exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/kubernetes/manifests
    - /var/lib/kubernetes
    - /var/lib/kubelet
    - /etc/kubernetes/kubelet
    - /etc/systemd/system/kubelet.service.d

- name: be sure we have the latest version of the kubelet from aws
  get_url:
    url: "{{ eks_s3_bucket_url }}/{{ k8s_version }}/{{ k8s_build_date }}/bin/linux/{{ kube_arch }}/kubelet"
    dest: /usr/bin/kubelet
    mode: a+x

- name: be sure the latest version of kubeconfig is present
  get_url:
    url: https://raw.githubusercontent.com/awslabs/amazon-eks-ami/master/files/kubelet-kubeconfig
    dest: /var/lib/kubelet/kubeconfig

- name: be sure the latest version of kubelet configuration is present
  get_url:
    url: https://raw.githubusercontent.com/awslabs/amazon-eks-ami/master/files/kubelet-config.json
    dest: /etc/kubernetes/kubelet/kubelet-config.json

- name: be sure the latest version of kubelet service is present
  get_url:
    url: https://raw.githubusercontent.com/awslabs/amazon-eks-ami/master/files/kubelet.service
    dest: /etc/systemd/system/kubelet.service

- name: be sure the kubelet is started and enabled
  systemd:
    name: kubelet
    state: started
    enabled: yes
    daemon_reload: yes
