---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/cleanup/tasks/centos.yml

- name: be sure the apt cache is clean
  apt:
    autoremove: yes
    autoclean: yes

